#! /bin/bash


cdn_server='cs5700cdnproject.ccs.neu.edu'

replicas_servers=("ec2-52-90-80-45.compute-1.amazonaws.com" "ec2-54-183-23-203.us-west-1.compute.amazonaws.com" "ec2-54-70-111-57.us-west-2.compute.amazonaws.com" "ec2-52-215-87-82.eu-west-1.compute.amazonaws.com" "ec2-52-28-249-79.eu-central-1.compute.amazonaws.com" "ec2-54-169-10-54.ap-southeast-1.compute.amazonaws.com" "ec2-52-62-198-57.ap-southeast-2.compute.amazonaws.com" "ec2-52-192-64-163.ap-northeast-1.compute.amazonaws.com" "ec2-54-233-152-60.sa-east-1.compute.amazonaws.com")



while getopts "p:o:n:u:i:" opts
do
	case $opts in
		p) port=$OPTARG;;

		o) origin_server=$OPTARG;;

		n) name=$OPTARG;;

		u) username=$OPTARG;;

		i) RSA_key_path=$OPTARG;;

		?) echo "Invalid arguement"
		exit 1;;
		esac
done

ssh -i $RSA_key_path $username@$cdn_server 'killall -u '$username' python'					#Kill the dnsserver

for replicas in "${replicas_servers[@]}"; do     				#kill the httpserver at each replica server
	ssh -i $RSA_key_path $username@$replicas 'killall -u'$username' python' 
done

